name: Virtuous
favicon: null
layout_spectrum: 0.49378
typography_spectrum: 0.79087
title: 'Virtuous, LLC - Film of the Highest Caliber'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dde1e0'
    - '#2f2e2c'
    - '#5d5d5d'
    - '#858686'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
