name: Virtuous
favicon: null
layout_spectrum: 0.18506
typography_spectrum: 0.79087
title: 'Virtuous, LLC - Film of the Highest Caliber'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dde1e0'
    - '#2f2e2c'
    - '#5d5d5d'
    - '#858686'
  brandStrength: 0.5
  lightness: 0.5602540725376457
  saturation: 0.4375
  rhythmicContrast: 0.9019381275866181
purpose: []
